openapi: 3.1.0
info:
  version: 1.0.0
  title: AppFeature2
  contact:
    email: contact@robowealth.co.th
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: ''
tags:
  - name: WatchList
    description: WatchList
  - name: Notification
    description: Notification
  - name: Note
    description: Note
servers:
  - url: https://example.com
paths:
  /api/v1/watch_list/list/{customer_id}:
    UpdateNameWatchList:
      post:
        tags:
          - WatchList
        summary: Update Name WatchList
        description: |
          Update Name WatchList
        operationId: Update_Name_WatchList
        parameters:
          - name: customer_id
            in: path
            description: customer id
            required: true
            schema:
              type: string
        security: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateNameWatchList'
          description: requestBody description
          required: true
        responses:
          '200':
            $ref: '#/components/responses/Update'
    DeleteAssets:
      post:
        tags:
          - WatchList
        summary: Delete Assets in WatchList
        description: |
          Delete Assets in WatchList
        operationId: Delete_Assets_in_WatchList
        parameters:
          - name: customer_id
            in: path
            description: customer id
            required: true
            schema:
              type: string
        security: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteAssetsInWatchList'
          description: requestBody description
          required: true
        responses:
          '200':
            $ref: '#/components/responses/Delete'
    PositionAssest:
      post:
        tags:
          - WatchList
        summary: PositionAssest
        description: |
          PositionAssest
        operationId: Position_Assest
        parameters:
          - name: customer_id
            in: path
            description: customer id
            required: true
            schema:
              type: string
        security: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PositionAssest'
          description: requestBody description
          required: true
        responses:
          '200':
            $ref: '#/components/responses/Update'
    get:
      tags:
        - WatchList
      summary: Get WatchList
      description: |
        Get WatchList
      operationId: Get_WatchList
      security: []
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WatchListGet'
    InsertAssetsToWatchList:
      post:
        tags:
          - WatchList
        summary: InsertAssetsToWatchList
        description: |
          InsertAssetsToWatchList
        operationId: Insert_Assets_To_WatchList
        parameters:
          - name: customer_id
            in: path
            description: customer id
            required: true
            schema:
              type: string
        security: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsertAssetsToWatchList'
          description: requestBody description
          required: true
        responses:
          '200':
            $ref: '#/components/responses/Update'
    MoveWatchList:
      post:
        tags:
          - WatchList
        summary: MoveWatchList
        description: |
          MoveWatchList
        operationId: Move_WatchList
        parameters:
          - name: customer_id
            in: path
            description: customer id
            required: true
            schema:
              type: string
        security: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoveWatchList'
          description: requestBody description
          required: true
        responses:
          '200':
            $ref: '#/components/responses/Update'
    CopyWatchList:
      post:
        tags:
          - WatchList
        summary: CopyWatchList
        description: |
          CopyWatchList
        operationId: Copy_WatchList
        parameters:
          - name: customer_id
            in: path
            description: customer id
            required: true
            schema:
              type: string
        security: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CopyWatchList'
          description: requestBody description
          required: true
        responses:
          '200':
            $ref: '#/components/responses/Update'
  /api/v1/watch_list/update-name:
    post:
      tags:
        - WatchList
      summary: Update Name WatchList
      description: |
        Update Name WatchList
      operationId: Update_Name_WatchList
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateNameWatchList'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Update'
  /api/v1/watch_list/delete-assets:
    post:
      tags:
        - WatchList
      summary: Delete Assets in WatchList
      description: |
        Delete Assets in WatchList
      operationId: Delete_Assets_in_WatchList
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteAssetsInWatchList'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Delete'
  /api/v1/watch_list/position-assets:
    post:
      tags:
        - WatchList
      summary: PositionAssest
      description: |
        PositionAssest
      operationId: Position_Assest
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PositionAssest'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Update'
  /api/v1/watch_list/insert-assets:
    post:
      tags:
        - WatchList
      summary: InsertAssetsToWatchList
      description: |
        InsertAssetsToWatchList
      operationId: Insert_Assets_To_WatchList
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsertAssetsToWatchList'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Update'
  /api/v1/watch_list/move:
    post:
      tags:
        - WatchList
      summary: MoveWatchList
      description: |
        MoveWatchList
      operationId: Move_WatchList
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MoveWatchList'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Update'
  /api/v1/watch_list/copy:
    post:
      tags:
        - WatchList
      summary: CopyWatchList
      description: |
        CopyWatchList
      operationId: Copy_WatchList
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CopyWatchList'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Update'
  /api/v1/notification/count-notification:
    get:
      tags:
        - Notification
      summary: CountNotification
      description: |
        CountNotification
      operationId: Count_Notification
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
      security: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountNotification'
        '400':
          $ref: '#/components/responses/Get'
  /api/v1/notification/notification-list:
    get:
      tags:
        - Notification
      summary: NotificationList
      description: |
        NotificationList
      operationId: Notification_List
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
        - name: type
          in: query
          description: type notification
          required: false
          schema:
            type: string
      security: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationList'
        '400':
          $ref: '#/components/responses/Get'
  /api/v1/notification/notification-read:
    post:
      tags:
        - Notification
      summary: NotificationRead
      description: |
        NotificationRead
      operationId: Notification_Read
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationRead'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Update'
  /api/v1/notification/notification-read-all:
    post:
      tags:
        - Notification
      summary: NotificationReadAll
      description: |
        NotificationReadAll
      operationId: Notification_Read_All
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
      security: []
      responses:
        '200':
          $ref: '#/components/responses/Update'
  /api/v1/notification/delete-notification:
    post:
      tags:
        - Notification
      summary: DeleteNotification
      description: |
        DeleteNotification
      operationId: Delete_Notification
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
      security: []
      responses:
        '200':
          $ref: '#/components/responses/Delete'
  /api/v1/notification/delete-notification-all:
    post:
      tags:
        - Notification
      summary: DeleteNotificationAll
      description: |
        DeleteNotificationAll
      operationId: Delete_Notification_All
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
      security: []
      responses:
        '200':
          $ref: '#/components/responses/Delete'
  /api/v1/note/count-note:
    get:
      tags:
        - Note
      summary: CountNote
      description: |
        CountNote
      operationId: Count_Note
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
      security: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountNote'
        '400':
          $ref: '#/components/responses/Get'
  /api/v1/note/insert-note-to-asset:
    post:
      tags:
        - Note
      summary: InsertNoteToAsset
      description: |
        InsertNoteToAsset
      operationId: Insert_Note_To_Asset
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsertNoteToAsset'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Update'
  /api/v1/note/inquiry-note-detail:
    get:
      tags:
        - Note
      summary: InquiryNoteDetail
      description: |
        InquiryNoteDetail
      operationId: Inquiry_Note_Detail
      parameters:
        - name: noteID
          in: query
          description: note id
          required: true
          schema:
            type: string
      security: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InquiryNoteDetail'
        '400':
          $ref: '#/components/responses/Get'
  /api/v1/note/update-note-detail:
    post:
      tags:
        - Note
      summary: UpdateNoteDetail
      description: |
        UpdateNoteDetail
      operationId: Update_Note_Detail
      parameters:
        - name: customer_id
          in: query
          description: customer id
          required: true
          schema:
            type: string
        - name: noteID
          in: query
          description: note id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateNoteDetail'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Update'
  /api/v1/note/delete-note:
    post:
      tags:
        - Note
      summary: DeleteNote
      description: |
        DeleteNote
      operationId: Delete_Note
      parameters:
        - name: customer_id
          in: query
          description: customer id
          required: true
          schema:
            type: string
        - name: noteID
          in: query
          description: note id
          required: true
          schema:
            type: string
      security: []
      responses:
        '200':
          $ref: '#/components/responses/Delete'
        '400':
          $ref: '#/components/responses/Problem_Delete'
  /api/v1/note/inquiry-article-list:
    get:
      tags:
        - Note
      summary: InquiryArticleList
      description: |
        InquiryArticleList
      operationId: Inquiry_Article_List
      parameters:
        - name: assetID
          in: query
          description: asset id
          required: true
          schema:
            type: string
      security: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InquiryArticleList'
        '400':
          $ref: '#/components/responses/Get'
  /api/v1/note/inquiry-bookmarked:
    get:
      tags:
        - Note
      summary: InquiryBookmarked
      description: |
        InquiryBookmarked
      operationId: Inquiry_Bookmarked
      parameters:
        - name: assetID
          in: query
          description: asset id
          required: true
          schema:
            type: string
      security: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InquiryBookmarked'
        '400':
          $ref: '#/components/responses/Get'
  /api/v1/note/insert-articleNote-asset:
    post:
      tags:
        - Note
      summary: InsertArticleNote
      description: |
        InsertArticleNote
      operationId: InsertArticleNote
      parameters:
        - name: customer_id
          in: query
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsertArticleNote'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Update'
  /api/v1/note/inquiry-count-all-type-note:
    get:
      tags:
        - Note
      summary: CountAllTypeNote
      description: |
        CountAllTypeNote
      operationId: Count_All_Type_Note
      parameters:
        - name: customerID
          in: query
          description: customer id
          required: true
          schema:
            type: string
      security: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountAllTypeNote'
        '400':
          $ref: '#/components/responses/Get'
  /api/v1/note/inquiry-asset-list-related-Article:
    get:
      tags:
        - Note
      summary: inquiryAssetListRelatedArticle
      description: |
        inquiryAssetListRelatedArticle
      operationId: inquiryAssetListRelatedArticle
      parameters:
        - name: customerID
          in: query
          description: customer id
          required: true
          schema:
            type: string
      security: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InquiryAssetListArticle'
        '400':
          $ref: '#/components/responses/Get'
  /api/v1/note/insert-bookmark:
    post:
      tags:
        - Note
      summary: InsertBookmark
      description: |
        InsertBookmark
      operationId: InsertBookmark
      parameters:
        - name: customer_id
          in: query
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsertBookmark'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Update'
  /api/v1/note/insert-bookmark-asset-list:
    post:
      tags:
        - Note
      summary: InsertBookmarkAssetList
      description: |
        InsertBookmarkAssetList
      operationId: Insert_Bookmark_AssetList
      parameters:
        - name: customer_id
          in: query
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsertBookmarkAssetList'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Update'
  /api/v1/note/inquiry-bookmarked-article-list:
    get:
      tags:
        - Note
      summary: InquiryBookmarkedAssetList
      description: |
        InquiryBookmarkedAssetList
      operationId: Inquiry_Bookmarked_Asset_List
      parameters:
        - name: customerID
          in: query
          description: customer id
          required: true
          schema:
            type: string
      security: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InquiryBookmarkedAssetList'
        '400':
          $ref: '#/components/responses/Get'
  /api/v1/note/delete-bookmarked-article:
    post:
      tags:
        - Note
      summary: DeleteBookmarkedArticle
      description: |
        DeleteBookmarkedArticle
      operationId: Delete_Bookmarked_Article
      parameters:
        - name: customer_id
          in: query
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteBookmarkedArticle'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Delete'
  /api/v1/note/delete-asset-by-bookmark:
    post:
      tags:
        - Note
      summary: DeleteAssetByBookmark
      description: |
        DeleteAssetByBookmark
      operationId: Delete_Asset_By_Bookmark
      parameters:
        - name: customer_id
          in: query
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteAssetByBookmark'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Delete'
  /api/v1/note/inquiry-card-note:
    get:
      tags:
        - Note
      summary: InquiryCardNote
      description: |
        InquiryCardNote
      operationId: Inquiry_Card_Note
      parameters:
        - name: customerID
          in: query
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestInquiryCardNote'
        description: requestBody description
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InquiryCardNote'
        '400':
          $ref: '#/components/responses/Get'
  /api/v1/note/inquiry-note-all:
    get:
      tags:
        - Note
      summary: InquiryNoteAll
      description: |
        InquiryNoteAll
      operationId: Inquiry_Note_All
      parameters:
        - name: customerID
          in: query
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestInquiryCardNote'
        description: requestBody description
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InquiryNoteAll'
        '400':
          $ref: '#/components/responses/Get'
  /api/v1/note/insert-alert-note:
    post:
      tags:
        - Note
      summary: InsertAlertNote
      description: |
        InsertAlertNote
      operationId: Insert_Alert_Note
      parameters:
        - name: customer_id
          in: query
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsertAlertNote'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Update'
  /api/v1/note/insert-portfolio-note:
    post:
      tags:
        - Note
      summary: InsertPortfolioNote
      description: |
        InsertPortfolioNote
      operationId: Insert_Portfolio_Note
      parameters:
        - name: customer_id
          in: query
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsertPortfolioNote'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Create'
  /api/v1/note/delete-portfolio-note:
    post:
      tags:
        - Note
      summary: DeletePortfolioNote
      description: |
        DeletePortfolioNote
      operationId: Delete_Portfolio_Note
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeletePortfolioNote'
        description: requestBody description
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Delete'
  /api/v1/note/delete-portfolio-note-all:
    post:
      tags:
        - Note
      summary: DeletePortfolioNoteAll
      description: |
        DeletePortfolioNoteAll
      operationId: Delete_Portfolio_Note_All
      parameters:
        - name: customer_id
          in: path
          description: customer id
          required: true
          schema:
            type: string
      security: []
      responses:
        '200':
          $ref: '#/components/responses/Delete'
components:
  schemas:
    WatchListGet:
      type: object
      properties:
        watch_list:
          type: array
          items:
            type: object
            properties:
              group_name:
                type: string
              data:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: int
                    product_code:
                      type: string
                    amc_code:
                      type: string
                    nav:
                      type: number
                      format: float
                    daily_gain_loss_percent:
                      type: number
                      format: float
                    tag:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: int
                          name_tag:
                            type: string
                          type_tag:
                            type: string
      example:
        watch_list:
          - group_name: Favorite_1
            data:
              - id: 1
                product_code: SET
                amc_code: Thailand set Index
                nav: 20.6543
                daily_gain_loss_percent: 1.38
                tag:
                  - id: 1
                    name_tag: Index
                    type_tag: ASSET
    UpdateNameWatchList:
      type: array
      items:
        type: object
        properties:
          watchlistName:
            type: string
          watchlistId:
            type: number
      example:
        - watchlistName: รายการโปรด1
          watchlistId: 1
        - watchlistName: รายการโปรด2
          watchlistId: 2
        - watchlistName: รายการโปรด3
          watchlistId: 3
        - watchlistName: รายการโปรด4
          watchlistId: 4
    DeleteAssetsInWatchList:
      type: object
      properties:
        watchlistId:
          type: number
        assets:
          type: array
          items:
            type: object
            properties:
              assetID:
                type: number
      example:
        watchlistId: 1
        assets:
          - assetID: 1
          - assetID: 2
          - assetID: 3
    PositionAssest:
      type: object
      properties:
        watchlistId:
          type: number
        assetId:
          type: number
        positionNew:
          type: number
        positionCurrent:
          type: number
      example:
        watchlistId: 1
        assetId: 1
        positionNew: 2
        positionCurrent: 1
    InsertAssetsToWatchList:
      type: object
      properties:
        assetId:
          type: number
        watchlistId:
          type: array
          items:
            type: number
      example:
        watchlistId:
          - 1
          - 2
          - 3
        assetId: 1
    MoveWatchList:
      type: object
      properties:
        currectWatchlist:
          type: number
        newWatchlist:
          type: number
        assets:
          type: array
          items:
            type: object
            properties:
              assetID:
                type: number
      example:
        currectWatchlist: 1
        newWatchlist: 2
        assets:
          - assetID: 1
          - assetID: 2
          - assetID: 3
    CopyWatchList:
      type: object
      properties:
        currectWatchlist:
          type: number
        newWatchlist:
          type: array
          items:
            type: number
        assets:
          type: array
          items:
            type: object
            properties:
              assetID:
                type: number
      example:
        currectWatchlist: 1
        newWatchlist:
          - 2
          - 3
        assets:
          - assetID: 1
          - assetID: 2
          - assetID: 3
    CountNotification:
      type: object
      properties:
        notificationCount:
          type: number
      example:
        notificationCount: 30
    NotificationList:
      type: object
      properties:
        today:
          type: object
          properties:
            announce:
              type: array
              items:
                type: object
                properties:
                  notificationId:
                    type: number
                  type:
                    type: string
                  title:
                    type: string
                  subTitle:
                    type: string
                  createdDate:
                    type: string
                  link:
                    type: string
            note_and_noti:
              type: array
              items:
                type: object
                properties:
                  notificationId:
                    type: number
                  type:
                    type: string
                  title:
                    type: string
                  subTitle:
                    type: string
                  createdDate:
                    type: string
                  link:
                    type: string
            transaction:
              type: array
              items:
                type: object
                properties:
                  notificationId:
                    type: number
                  type:
                    type: string
                  title:
                    type: string
                  subTitle:
                    type: string
                  createdDate:
                    type: string
                  link:
                    type: string
            assets:
              type: array
              items:
                type: object
                properties:
                  notificationId:
                    type: number
                  type:
                    type: string
                  title:
                    type: string
                  subTitle:
                    type: string
                  createdDate:
                    type: string
                  link:
                    type: string
            etc:
              type: array
              items:
                type: object
                properties:
                  notificationId:
                    type: number
                  type:
                    type: string
                  title:
                    type: string
                  subTitle:
                    type: string
                  createdDate:
                    type: string
                  link:
                    type: string
      example:
        today:
          announce:
            - notification_id: 1
              type: announce
              title: เปิดเผย4 สไตล์การลงทุน ...
              sub_title: เปิดเผย4 สไตล์การลงทุน ...
              created_date: 1680199522
              link: ''
          note_and_noti:
            - notification_id: 1
              type: note_and_noti
              title: k-supstar-ssfx
              sub_title: ราคาเปลี่ยนแปลง
              created_date: 1680199522
              link: ''
              ....: ''
          transaction:
            - notification_id: 1
              type: transaction
              title: คำสั่งซื้อ k-supstar-ssfx
              sub_title: จำนวนหน่วย
              created_date: 1680199522
              link: ''
              ....: ''
          assets:
            - notification_id: 1
              type: assets
              title: คำสั่งซื้อ k-supstar-ssfx
              sub_title: จำนวนหน่วย
              created_date: 1680199522
              link: ''
              ....: ''
          etc:
            - notification_id: 1
              type: etc
              title: คำสั่งซื้อ k-supstar-ssfx
              sub_title: จำนวนหน่วย
              created_date: 1680199522
              link: ''
              ....: ''
    NotificationRead:
      type: object
      properties:
        notificationId:
          type: number
      example:
        notificationId: 1
    CountNote:
      type: object
      properties:
        note:
          type: number
        article:
          type: number
        allNote:
          type: number
      example:
        note: 4
        article: 4
        allNote: 8
    InsertNoteToAsset:
      type: object
      properties:
        assetId:
          type: number
        portGraph:
          type: boolean
        title:
          type: string
        details:
          type: string
        tag:
          type: array
          item:
            type: number
      example:
        assetId: 1
        portGraph: true
        title: หัวข้อโน๊ต
        details: จดไว้
        tag:
          - 1
          - 2
          - 3
    InquiryNoteDetail:
      type: object
      properties:
        noteId:
          type: number
        assetId:
          type: number
        portGraph:
          type: boolean
        title:
          type: string
        details:
          type: string
        tag:
          type: array
          item:
            type: number
      example:
        noteID: 1
        assetId: 1
        portGraph: true
        title: หัวข้อโน๊ต
        details: จดไว้
        tag:
          - 1
          - 2
          - 3
    UpdateNoteDetail:
      type: object
      properties:
        portGraph:
          type: boolean
        title:
          type: string
        details:
          type: string
        tag:
          type: array
          item:
            type: number
      example:
        portGraph: true
        title: หัวข้อโน๊ต
        details: จดไว้
        tag:
          - 1
          - 2
          - 3
    InquiryArticleList:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              group:
                type: string
              contents:
                type: array
                items:
                  type: object
                  properties:
                    feed_id:
                      type: integer
                    feed_title:
                      type: string
                    dateTime:
                      type: integer
                    tag:
                      type: array
                      items:
                        type: string
      example:
        data:
          - group: แนะนำ
            contents:
              - feed_id: 1
                fee_title: นโยบายกระตุ้นเศรษฐกิจหลังเปิดประเทศ
                dateTime: 1678637816
                tag:
                  - ข่าวสาร
                  - สินค้า
              - feed_id: 2
                fee_title: นโยบายกระตุ้นเศรษฐกิจหลังเปิดประเทศ
                dateTime: 1678637816
                tag:
                  - ข่าวสาร
                  - สินค้า
          - group: ทั้งหมด
            contents:
              - feed_id: 1
                fee_title: นโยบายกระตุ้นเศรษฐกิจหลังเปิดประเทศ
                dateTime: 1678637816
                tag:
                  - ข่าวสาร
                  - สินค้า
              - feed_id: 2
                fee_title: นโยบายกระตุ้นเศรษฐกิจหลังเปิดประเทศ
                dateTime: 1678637816
                tag:
                  - ข่าวสาร
                  - สินค้า
          - group: Wealth
            contents:
              - feed_id: 1
                fee_title: นโยบายกระตุ้นเศรษฐกิจหลังเปิดประเทศ
                dateTime: 1678637816
                tag:
                  - ข่าวสาร
                  - สินค้า
              - feed_id: 2
                fee_title: นโยบายกระตุ้นเศรษฐกิจหลังเปิดประเทศ
                dateTime: 1678637816
                tag:
                  - ข่าวสาร
                  - สินค้า
    InquiryBookmarked:
      type: object
      properties:
        feedList:
          type: array
          items:
            type: object
            properties:
              feed_id:
                type: integer
              feed_title:
                type: string
              dateTime:
                type: integer
              tag:
                type: array
                items:
                  type: string
      example:
        feedList:
          - feed_id: 1
            fee_title: นโยบายกระตุ้นเศรษฐกิจหลังเปิดประเทศ
            dateTime: 1678637816
            tag:
              - ข่าวสาร
              - สินค้า
          - feed_id: 2
            fee_title: นโยบายกระตุ้นเศรษฐกิจหลังเปิดประเทศ
            dateTime: 1678637816
            tag:
              - ข่าวสาร
              - สินค้า
    InsertArticleNote:
      type: object
      properties:
        feedList:
          type: array
          item:
            type: number
      example:
        feedList:
          - 1
          - 2
          - 3
          - 4
    CountAllTypeNote:
      type: object
      properties:
        asset:
          tpye: number
        portfolio:
          tpye: number
        bookmark:
          tpye: number
      example:
        asset: 7
        bookmark: 8
        portfolio: 1
    InquiryAssetListArticle:
      type: object
      properties:
        data:
          type: array
          item:
            type: object
            properties:
              groupName:
                type: string
              assets:
                tpye: array
                item:
                  type: object
                  properties:
                    assetId:
                      type: number
                    assetName:
                      type: string
                    assetSubName:
                      type: string
      example:
        data:
          - groupName: แนะนำ
            assets:
              - assetId: 1
                assetName: K-2500
                assetSubName: K Lifestyle Fund 2500
    InsertBookmark:
      type: object
      properties:
        feedId:
          type: number
        customerID:
          type: number
      example:
        feedId: 1
        customerID: 1
    InsertBookmarkAssetList:
      type: object
      properties:
        feedId:
          type: number
        assets:
          type: array
          item:
            type: number
      example:
        feedId: 1
        assets:
          - 1
          - 2
          - 3
    InquiryBookmarkedAssetList:
      type: object
      properties:
        bookmark:
          type: array
          items:
            type: object
            properties:
              feed_id:
                type: integer
              feed_title:
                type: string
              dateTime:
                type: integer
              tag:
                type: array
                items:
                  type: string
      example:
        bookmark:
          - feed_id: 1
            fee_title: นโยบายกระตุ้นเศรษฐกิจหลังเปิดประเทศ
            dateTime: 1678637816
            tag:
              - ข่าวสาร
              - สินค้า
          - feed_id: 2
            fee_title: นโยบายกระตุ้นเศรษฐกิจหลังเปิดประเทศ
            dateTime: 1678637816
            tag:
              - ข่าวสาร
              - สินค้า
    DeleteBookmarkedArticle:
      type: object
      properties:
        bookmarkId:
          type: number
      example:
        bookmarkId: 1
    DeleteAssetByBookmark:
      type: object
      properties:
        assetId:
          type: number
        bookmarkId:
          type: number
      example:
        bookmarkId: 1
        assetId: 1
    RequestInquiryCardNote:
      type: object
      properties:
        assetId:
          type: number
      example:
        assetId: 1
    InquiryCardNote:
      type: object
      properties:
        note:
          type: array
          items:
            type: object
            properties:
              noteId:
                type: number
              type:
                type: string
              title:
                type: string
              createdDate:
                type: string
              link:
                type: string
        countAllNote:
          type: number
      example:
        note:
          - noteId: 1
            type: note_and_noti
            title: บันทึกการลงทุน1
            created_date: 1680199522
            link: ''
            ....: ''
          - noteId: 2
            type: note_and_noti
            title: บันทึกการลงทุน1
            created_date: 1680199522
            link: ''
            ....: ''
          - noteId: 3
            type: note_and_noti
            title: บันทึกการลงทุน1
            created_date: 1680199522
            link: ''
            ....: ''
        countAllNote: 7
    InquiryNoteAll:
      type: object
      properties:
        note:
          type: array
          items:
            type: object
            properties:
              noteId:
                type: number
              type:
                type: string
              title:
                type: string
              createdDate:
                type: string
              link:
                type: string
        transaction:
          type: array
          items:
            type: object
            properties:
              transaction:
                type: string
              assetName:
                type: string
              paymentAmount:
                type: number
              status:
                type: boolean
              assetSubName:
                type: string
      example:
        note:
          - noteId: 1
            type: note_and_noti
            title: บันทึกการลงทุน1
            created_date: 1680199522
            link: ''
            ....: ''
          - noteId: 2
            type: note_and_noti
            title: บันทึกการลงทุน1
            created_date: 1680199522
            link: ''
            ....: ''
          - noteId: 3
            type: note_and_noti
            title: บันทึกการลงทุน1
            created_date: 1680199522
            link: ''
            ....: ''
        transaction:
          - transaction: sell
            assetName: K-2500
            assetSubName: กองทุนเปิดเค ไลฟ์สไตล์ 2500
            paymentAmount: 2000
            status: true
    InsertAlertNote:
      type: object
      properties:
        priceAlert:
          type: object
          properties:
            status:
              type: boolean
            value:
              type: number
        currentPriceAlert:
          type: object
          properties:
            status:
              type: boolean
            value:
              type: number
        notifyOnDate:
          type: object
          properties:
            status:
              type: boolean
            value:
              type: null
      example:
        priceAlert:
          status: true
          value: 29.77
        currentPriceAlert:
          status: true
          value: 10
        notifyOnDate:
          status: true
          value: 1680199522
    InsertPortfolioNote:
      type: object
      properties:
        title:
          type: string
        details:
          type: string
      example:
        title: portfolio
        details: จดบันทึก
    DeletePortfolioNote:
      type: object
      properties:
        portfolioId:
          type: number
      example:
        portfolioId: 1
  responses:
    Update:
      description: Success
      content:
        application/json:
          schema:
            type: object
            additionalProperties: true
            minProperties: 1
            description: The Success Details JSON Object.
            properties:
              status:
                type: integer
                description: The HTTP status code.
                example: 200
              message:
                type: string
                example: update success message
    Delete:
      description: Success
      content:
        application/json:
          schema:
            type: object
            additionalProperties: true
            minProperties: 1
            description: The Success Details JSON Object.
            properties:
              status:
                type: integer
                description: The HTTP status code.
                example: 200
              message:
                type: string
                example: delete success message
    Get:
      description: Failure
      content:
        application/json:
          schema:
            type: object
            additionalProperties: true
            minProperties: 1
            description: The Failure Details JSON Object.
            properties:
              status:
                type: integer
                description: The HTTP status code.
                example: 400
              message:
                type: string
                example: get failure message
    Problem_Delete:
      description: Failure
      content:
        application/json:
          schema:
            type: object
            additionalProperties: true
            minProperties: 1
            description: The Failure Details JSON Object.
            properties:
              status:
                type: integer
                description: The HTTP status code.
                example: 400
              message:
                type: string
                example: delete failure message
    Create:
      description: Success
      content:
        application/json:
          schema:
            type: object
            additionalProperties: true
            minProperties: 1
            description: The Success Details JSON Object.
            properties:
              status:
                type: integer
                description: The HTTP status code.
                example: 200
              message:
                type: string
                example: create success message
